export const endpoints = {
  auth: {
    register: "/auth/register",
    login: "/auth/login",
    google: "/auth/google",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    me: "/auth/me",
  },
  companies: {
    me: "/companies/me",
    update: "/companies/me",
    create: "/companies",
  },
  subscriptions: {
    plans: "/subscriptions/plans",
    start: "/subscriptions",
    me: "/subscriptions/me",
    changePlan: "/subscriptions/me/plan",
    cancel: "/subscriptions/me/cancel",
    invoices: "/subscriptions/me/invoices",
    paymentMethod: "/subscriptions/me/payment-method",
  },
  tenants: {
    list: "/tenants",
    byId: (id: string) => `/tenants/${id}`,
    suspend: (id: string) => `/tenants/${id}/suspend`,
  },
  billing: {
    list: "/billing",
    plans: "/billing/plans",
    retry: (id: string) => `/billing/${id}/retry`,
  },
  usage: {
    summary: "/usage",
    apiVolume: "/usage/api-volume",
  },
  support: {
    tickets: "/support/tickets",
  },
  settings: {
    flags: "/settings/flags",
    citations: "/settings/citations",
    template: "/settings/template",
  },
  inspections: {
    list: "/inspections",
    byId: (id: string) => `/inspections/${id}`,
    photos: (id: string) => `/inspections/${id}/photos`,
    damageTags: (id: string) => `/inspections/${id}/damage-tags`,
    testSquares: (id: string) => `/inspections/${id}/test-squares`,
    approve: (id: string) => `/inspections/${id}/approve`,
  },
  jobs: {
    list: "/jobs",
    create: "/jobs",
    byId: (id: string) => `/jobs/${id}`,
    update: (id: string) => `/jobs/${id}`,
    assign: (id: string) => `/jobs/${id}/assign`,
    unassign: (id: string) => `/jobs/${id}/unassign`,
    status: (id: string) => `/jobs/${id}/status`,
    cancel: (id: string) => `/jobs/${id}/cancel`,
    bulkAssign: "/jobs/bulk-assign",
  },
  reports: {
    list: "/reports",
    byId: (id: string) => `/reports/${id}`,
    submit: (id: string) => `/reports/${id}/submit`,
    startReview: (id: string) => `/reports/${id}/review`,
    approve: (id: string) => `/reports/${id}/approve`,
    reject: (id: string) => `/reports/${id}/reject`,
    requestChanges: (id: string) => `/reports/${id}/request-changes`,
    shareById: (id: string) => `/reports/${id}/share`,
    review: (jobId: string) => `/reports/jobs/${jobId}/review`,
    byJob: (jobId: string) => `/reports/jobs/${jobId}`,
    narrative: (jobId: string) => `/reports/jobs/${jobId}/narrative`,
    generate: (jobId: string) => `/reports/jobs/${jobId}/generate`,
    share: (jobId: string) => `/reports/jobs/${jobId}/share`,
  },
  staff: {
    list: "/users/inspectors",
    create: "/users/inspectors",
    status: (id: string) => `/users/inspectors/${id}/status`,
    byId: (id: string) => `/users/inspectors/${id}`,
    history: (id: string) => `/users/inspectors/${id}/history`,
    resetPassword: (id: string) => `/users/inspectors/${id}/reset-password`,
    reassignJobs: (id: string) => `/users/inspectors/${id}/reassign-jobs`,
  },
  officeStaff: {
    list: "/users/staff",
    create: "/users/staff",
    byId: (id: string) => `/users/staff/${id}`,
    status: (id: string) => `/users/staff/${id}/status`,
  },
  companyUsers: {
    list: "/users/company",
  },
  codes: {
    citations: "/checklists/citations",
    citation: (id: string) => `/checklists/citations/${id}`,
    checklists: "/checklists",
    checklist: (id: string) => `/checklists/${id}`,
    checklistDefault: "/checklists/default",
  },
  branding: {
    get: "/branding",
    save: "/branding",
  },
  templates: {
    list: "/templates",
    create: "/templates",
    default: "/templates/default",
    byId: (id: string) => `/templates/${id}`,
  },
  analytics: {
    company: "/analytics/company",
    platform: "/analytics/platform",
  },
  dashboard: {
    company: "/dashboard/company",
    platform: "/dashboard/platform",
  },
} as const
