export const ROUTES = {
  home: "/",
  login: "/login",
  signup: "/signup",
  superAdmin: {
    login: "/roofclaim/admin",
    users: "/roofclaim/admin/users",
    subscriptions: "/roofclaim/admin/subscriptions",
  },
  platform: {
    root: "/platform",
    dashboard: "/platform/dashboard",
    tenants: "/platform/tenants",
    billing: "/platform/billing",
    usage: "/platform/usage",
    settings: "/platform/settings",
    support: "/platform/support",
  },
  company: {
    root: "/company",
    dashboard: "/company/dashboard",
    jobs: "/company/jobs",
    job: (id: string) => `/company/jobs/${id}`,
    staff: "/company/staff",
    organization: "/company/organization",
    billing: "/company/billing",
    codes: "/company/codes",
    reports: "/company/reports",
    report: (id: string) => `/company/reports/${id}`,
    branding: "/company/branding",
    templates: "/company/templates",
    analytics: "/company/analytics",
  },
  onboarding: {
    organization: "/onboarding/organization",
    subscription: "/onboarding/subscription",
  },
} as const
